### ISSUE TITLE
About image collections

### ISSUE THREAD

**Issue by shuilinggirl** [rsinghlab/MADDi#14]
I am already able to access the ADNI dataset and I am curious about how you chose image_ Collections. Because according to the paper, I cannot obtain the corresponding results. Can you share the method of selecting a dataset or add me to your ADNI researcher so that I can download your image collection.

**Comment by michalg04** [comment]
Hi there! Thanks for reading our work. We followed the pre-processing and image selections specified in the Appendix of this paper: https://www.nature.com/articles/s41598-020-74399-w
I cannot share account info, unfortunately. I have heard from other researchers that the imaging formatting has changed since 2021 (which is when I obtained my images), so that could lead to some issues.
