### ISSUE TITLE
I can't find any key "DX" on DXSUM_PDXCONV_ADNIALL.csv

### ISSUE THREAD

**Issue by EuijinMisp** [rsinghlab/MADDi#3]
Hello,

Thank you for opening your great study!

I got a 'DX' Key Error while running /general/diagnosis_making.ipynb. 
<img width="690" alt="image" src="https://user-images.githubusercontent.com/30389053/203181974-905cbfd6-9a52-4521-9954-0bbde4925063.png">

So, I check all keys on DXSUM_PDXCONV_ADNIALL.csv and other csv files.
However, all keys related to DX are DXCAHNGE, DXCURREN, and a lot of words starting DX.

I'm confused which word do you mean?

**Comment by michalg04** [comment]
Hi there! When I downloaded the data (back in 2021), there was a "DX" column. DX stands for diagnosis, and it was a stand-alone column, in addition to being a pre-fix to other columns. Based on your error, it looks like that column is no longer there. It is possible that since 2021, that column has been removed from the database at ADNI. I used that diagnosis column to find some consensus on the correct diagnosis of each patient. Hopefully you can find it or download an earlier version of the file. You can always contact ADNI to see if they can help you locate it!
