### ISSUE TITLE
Regarding ADNI dataset 

### ISSUE THREAD

**Issue by simran131997** [rsinghlab/MADDi#4]
I  came across your paper and planning to implementing it. We have got access to the ADNI dataset from college but I am unable to find specific dataset used in the source code. 
Can you share the exact dataset or can you help.me find it by pointing it out in ADNI with steps?
 It would be extremely thankful if you can help me with this.

**Comment by michalg04** [comment]
Hi there,
I downloaded the imaging dataset in 2021 so unfortunately if the data has been updated since then it is difficult to pin point all the same exact files, but there should be a significant overlap if you download now. If you follow the data section in the paper and look for the studies we used (ADNI 1,2, and GO), that should be the filtering criteria you use on the ADNI website. Hope that helps!
