### ISSUE TITLE
Couldn't create the file "overlap_test_set.csv"

### ISSUE THREAD

**Issue by ManojKumar002** [rsinghlab/MADDi#6]
To execute "**preprocess_genetic/create_genetic_dataset.ipynb**" , we need the dataset **"overlap_test_set.csv"**, which will be created after executing **"preprocess_overlap/create_overlap_dataset.ipynb"**. 

But to execute **"preprocess_overlap/create_overlap_dataset.ipynb"**  we need the dataset **"vcf_select.pkl"** , which will be created after executing "**preprocess_genetic/create_genetic_dataset.ipynb**".

In simple words the two files "**preprocess_genetic/create_genetic_dataset.ipynb**"  and  **"preprocess_overlap/create_overlap_dataset.ipynb"** depends on each other to execute.

Can you please give a clarification to this?

**Comment by michalg04** [comment]
Hi there,
Thank you for pointing this out! Yes - this is my mistake that was created when cleaning the code! I apologize and will work on fixing it now. The order should be to create the "all_vcfs.pkl" file first, then use it in the create_overlap_dataset.ipynb instead of the "vcf_select.pkl". I will make that correction in the code. Thanks!
