### ISSUE TITLE
Regarding the source of dataset

### ISSUE THREAD

**Issue by ManojKumar002** [rsinghlab/MADDi#8]
Hello,
In the file preprocess_genetic/concat_vcfs.py we are facing multiple error due to the incompatible dataset.Can you please share the exact link of dataset in ADNI website or its better if you provide the sample vcf file.

**Comment by michalg04** [comment]
Hi there,
Thank you for reaching out!
The supplementary file describes exactly which genetic files were used. On the ADNI website, you can filter based on the criteria mentioned in the supplementary. I cannot share any ADNI sample files, and I am hesitant to share a link since the website has changes since 2021 when I accessed the data. Hope you understand!

**Comment by ManojKumar002** [comment]
Hello,
Recently we found that the dataset which we were using is 2013 version and the the dataset which you had worked is on 2014 version.
Thank you.

**Comment by sydat2701** [comment]
> Hello, In the file preprocess_genetic/concat_vcfs.py we are facing multiple error due to the incompatible dataset.Can you please share the exact link of dataset in ADNI website or its better if you provide the sample vcf file.

Hi, I'm facing the same problem with you.  Did you solve it? If yes, could you share the dataset with me, because I also really want to experience with this work. Thank you so much for your help.
